version: '3.8'
services:
  adot-collector:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    command: --config otel-local-config.yaml
    ports:
      - "4317:4317"
      - "55680:55680"
      - "8889:8888"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=ap-northeast-1
    volumes:
      - ./adot-config.yaml:/otel-local-config.yaml