version: '3.8'
services:
  adot-collector:
    image: public.ecr.aws/aws-observability/aws-otel-collector:latest
    command: --config otel-local-config.yaml
    ports:
      - "4317:4317"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=ap-northeast-1
    volumes:
      - ./adot-config.yaml:/otel-local-config.yaml
  backend:
    image: adot-sample-backend
    container_name: adot-sample-backend
    build:
      context: ./backend
      dockerfile: ./build/Dockerfile
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:9090"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      - adot-collector
  bff:
    image: adot-sample-bff
    container_name: adot-sample-bff
    build:
      context: ./bff
      dockerfile: ./build/Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      - adot-collector